version: "3.4"
services:
    registry:
        image: omarcovelho/registry
        ports:
            - "8761:8080"
        networks:
            - vpc
        environment:
            EUREKA_USER: "${EUREKA_USER}"
            EUREKA_PASSWORD: "${EUREKA_PASSWORD}"
        healthcheck:
            test: ["CMD", "curl", "--fail", "--silent", "localhost:8080/actuator/health 2>&1 | grep UP || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
    config:
        depends_on:
            - registry
        image: omarcovelho/config
        environment:
            EUREKA_ADDRESS: "${EUREKA_ADDRESS}"
            CONFIG_USER: "${CONFIG_USER}"
            CONFIG_PASSWORD: "${CONFIG_PASSWORD}"
            SPRING_PROFILES_ACTIVE: native
        networks:
            - vpc
        ports:
          - "8888:8080"
        healthcheck:
            test: ["CMD", "curl", "--fail", "--silent", "localhost:8080/actuator/health 2>&1 | grep UP || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
    store:
        depends_on:
            - mongo
            - config
            - registry
        image: omarcovelho/store
        environment:
            EUREKA_ADDRESS: "${EUREKA_ADDRESS}"
            CONFIG_USER: "${CONFIG_USER}"
            CONFIG_PASSWORD: "${CONFIG_PASSWORD}"
        networks:
            - vpc
        healthcheck:
            test: ["CMD", "curl", "--fail", "--silent", "localhost:8080/actuator/health 2>&1 | grep UP || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
    sales:
        depends_on:
            - mongo
            - config
            - registry
        image: omarcovelho/sales
        environment:
            EUREKA_ADDRESS: "${EUREKA_ADDRESS}"
            CONFIG_USER: "${CONFIG_USER}"
            CONFIG_PASSWORD: "${CONFIG_PASSWORD}"
        networks:
            - vpc
        healthcheck:
            test: ["CMD", "curl", "--fail", "--silent", "localhost:8080/actuator/health 2>&1 | grep UP || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
    users:
        depends_on:
            - mongo
            - config
            - registry
        image: omarcovelho/users
        environment:
            EUREKA_ADDRESS: "${EUREKA_ADDRESS}"
            CONFIG_USER: "${CONFIG_USER}"
            CONFIG_PASSWORD: "${CONFIG_PASSWORD}"
        networks:
            - vpc
        healthcheck:
            test: ["CMD", "curl", "--fail", "--silent", "localhost:8080/actuator/health 2>&1 | grep UP || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
    gateway:
        depends_on:
            - mongo
            - config
            - registry
        image: omarcovelho/gateway
        environment:
            EUREKA_ADDRESS: "${EUREKA_ADDRESS}"
            CONFIG_USER: "${CONFIG_USER}"
            CONFIG_PASSWORD: "${CONFIG_PASSWORD}"
        ports:
            - "80:8080"
        networks:
            - vpc
        healthcheck:
            test: ["CMD", "curl", "--fail", "--silent", "localhost:8080/actuator/health 2>&1 | grep UP || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
    mongo:
        image: "mongo"
        volumes:
            - "storedb:/data/db"
        ports:
           - "27017:27017"
        networks:
            - vpc
    mongo-express:
        image: mongo-express
        ports:
            - 8090:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
        networks:
            - vpc
volumes:
    storedb:

networks:
    vpc:
        driver: bridge