version: "3"
services:
    mongo:
        image: "mongo"
        volumes:
            - "storedb:/data/db"
        ports:
            - "27017:27017"
    mongo-express:
        image: mongo-express
        ports:
            - 8090:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
volumes:
    storedb: