server:
  port: 8083
spring:
  data:
    mongodb:
      database: users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

debug: true
logging.level:
  org:
    springframework:
      security: TRACE