server:
  port: 8888

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: store
          uri: lb://store
          predicates:
          - Path=/store/**
        - id: sales
          uri: lb://sales
          predicates:
          - Path=/sale/**
