spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 131410492823-j0tfr05n49cqh3hrftvlglcehh7eskcg.apps.googleusercontent.com
            client-secret: bi7TH03CVHR4KWZmkvx2tqd-

users:
  ribbon:
    listOfServers: localhost:8083

logging.level.root: DEBUG

zuul:
  routes:
    discovery.locator.enabled: true
    store:
      path: /api/store/**
      stripPrefix: false
      url: http://localhost:8081
    sales:
      path: /api/sale/**
      stripPrefix: false
      url: http://localhost:8082
    actuator:
      path: /actuator/**
      url: forward:/actuator
    ui:
      path: /**
      url: http://localhost:8085