spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 131410492823-j0tfr05n49cqh3hrftvlglcehh7eskcg.apps.googleusercontent.com
            client-secret: bi7TH03CVHR4KWZmkvx2tqd-

users:
  ribbon:
    listOfServers: localhost:8083

zuul:
  routes:
    discovery.locator.enabled: true
    store:
      path: /api/store/**
      stripPrefix: false
      serviceId: store
    sales:
      path: /api/sale/**
      stripPrefix: false
      serviceId: sale
    ui:
      path: /**
      serviceId: ui