spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 131410492823-j0tfr05n49cqh3hrftvlglcehh7eskcg.apps.googleusercontent.com
            client-secret: bi7TH03CVHR4KWZmkvx2tqd-

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

zuul:
  routes:
    discovery.locator.enabled: true
    store:
      path: /api/store/**
      stripPrefix: true
      serviceId: store
    sales:
      path: /api/sale/**
      stripPrefix: true
      serviceId: sale
    ui:
      path: /ui/**
      stripPrefix: true
      serviceId: ui

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging.level.root: TRACE