#!/bin/bash
mvn spring-boot:build-image -pl store,sales,registry,gateway,users,config,ui
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push "$DOCKER_USERNAME/config"
docker push "$DOCKER_USERNAME/gateway"
docker push "$DOCKER_USERNAME/registry"
docker push "$DOCKER_USERNAME/sales"
docker push "$DOCKER_USERNAME/store"
docker push "$DOCKER_USERNAME/users"
docker push "$DOCKER_USERNAME/ui"

