#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push "$DOCKER_USERNAME/config"
docker push "$DOCKER_USERNAME/gateway"
docker push "$DOCKER_USERNAME/registry"
docker push "$DOCKER_USERNAME/sales"
docker push "$DOCKER_USERNAME/store"
docker push "$DOCKER_USERNAME/users"
docker push "$DOCKER_USERNAME/ui"

