spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 131410492823-j0tfr05n49cqh3hrftvlglcehh7eskcg.apps.googleusercontent.com
            client-secret: bi7TH03CVHR4KWZmkvx2tqd-

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

zuul:
  routes:
    discovery.locator.enabled: true
    routes:
      store:
        path: /store/**
        stripPrefix: true
      sales:
        path: /sale/**
        stripPrefix: true