spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 131410492823-j0tfr05n49cqh3hrftvlglcehh7eskcg.apps.googleusercontent.com
            client-secret: '{cipher}33971f9bf99350db2f4f58e2869b627598cff7b2f1dd47afb98dc1b0814a0bbabf8840776e2e7a138dc5503b63858d9a'

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

zuul:
  routes:
    discovery.locator.enabled: true
    routes:
      store:
        prefix: /api
        path: /store/**
        stripPrefix: true
      sales:
        prefix: /api
        path: /api/sale/**
        stripPrefix: true
      ui:
        path: /**
        stripPrefix: true

logging.level.root: DEBUG